version: "3.9"

services:
  tasks:
    networks:
      - new
    build:
      context: ./
      dockerfile: Dockerfile
    command: ["--storage=${STORAGE}"]
    ports:
      - "8080:8080"
    depends_on:
      - migrate

  db:
    restart: always
    image: postgres:latest
    networks:
      - new
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: pg_isready --username "postgres" --dbname "postgres"
      interval: 1s
      retries: 3
      timeout: 5s

  migrate:
    image: migrate/migrate:latest
    volumes:
      - ./migrations:/migrations
    depends_on:
      db:
        condition: service_healthy
    networks:
      - new
    command: '-path /migrations/ -database "postgres://postgres:${POSTGRES_PASSWORD}@db:5432/postgres?sslmode=disable" up'

networks:
  new:
    driver: bridge